[package]
name = "android_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }


[[bin]]
name = "publisher"
path = "src/publisher.rs"
